### ISSUE TITLE
[Perf] Remove eslint linebreak-style 

### ISSUE THREAD

**Issue by hojihun5516** [teamthesol/boggler#44]
**What features will you improve?**
eslint lets you use to make debugging more seamless and to write clearer code.

**How do you improve the functionality?**
We set the code rules we want and exclude them if they violate the eslint rules

**Do you have any additional comments before leave?**
If there is a code rule that we need to keep, please write down

**Comment by rayleighko** [comment]
Done. https://github.com/teamthesol/boggler/pull/83
