### ISSUE TITLE
[Bug] The playback time and wave form time do not match.

### ISSUE THREAD

**Issue by KangGilHwan** [teamthesol/boggler#50]
**Describe the bug**
The playback time and wave form time do **not match.**

**Additional context**
I think I need to get the current playback time from the player and match it.
Now, every 0.1 seconds, the player runs the callback, I am modifying the state.

**Comment by rayleighko** [comment]
This is because the audio cursor is not initialized. What about adding a function to initialize the cursor for this?

**Comment by KangGilHwan** [comment]
@rayleighko  Thank you for letting me know the bug. I have now resolved the issue and will further reflect your opinion!
