### ISSUE TITLE
[Front-feature] Progress Bar

### ISSUE THREAD

**Issue by hojihun5516** [teamthesol/boggler#53]
**Is your feature request related to a problem? Please describe.**
The screen is frozen while we convert the voice file into text.

**Describe the solution you'd like**
The user should be able to recognize that the work is in progress.

**Describe alternatives you've considered**
We can use react-progressbar. But there is something we need to consider.
I can't get figures on the progress of the work.

**Comment by hojihun5516** [comment]
I forgot. We have already made progressBar.
So I will try it

**Comment by rayleighko** [comment]
done to styling.
