### ISSUE TITLE
[Bug] Audio file type and empty file 

### ISSUE THREAD

**Issue by hojihun5516** [teamthesol/boggler#54]
**Describe the bug**
If the audio file is not wav, the function is disabled

**To Reproduce**

1. Upload non-wavfile files
2. Click on submit button
3. It is not working
or
1.Do not upload any files
2.You can see server error 

**Expected behavior**
Show error message  

**Desktop (please complete the following information):**

- OS: [Windows]
- Browser [chrome]

**Comment by rayleighko** [comment]
you can solve issue - `Upload non-wav files` with edit form components.

**Comment by rayleighko** [comment]
I have modified the form so that I can only enter wav files in https://github.com/teamthesol/boggler/pull/58,  related to styling modifications.

**Comment by hojihun5516** [comment]
done

**Comment by rayleighko** [comment]
https://github.com/teamthesol/boggler/pull/66
