### ISSUE TITLE
[Bug] AudioProgressbar is set when clicks submit button without uploading file.

### ISSUE THREAD

**Issue by rayleighko** [teamthesol/boggler#63]
**Describe the bug**
AudioProgressbar is set when clicks submit button without uploading file. AudioProgressbar will is only set when click submit button with uploading file.

**To Reproduce**

1. Click on 'Submit' button.
2. See error

**Comment by hojihun5516** [comment]
done

**Comment by rayleighko** [comment]
https://github.com/teamthesol/boggler/pull/66
